// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"; // if using self-hosted font
import { Source_Sans_3 } from "next/font/google"; // closest match to Source Sans Pro

// Body font
const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans.variable} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
